# <center>Numerical analysis</center>
## <center>Neville's formula; Newton's diveded-difference formula</center>

### <center>Yong Yang</center>
#### <center>yongyang@nuaa.edu.cn</center>

## Review

* Problem: find the polynomial passing through $(n+1)$ points $(x_i,y_i)$
* Lagrange interpolation polynomial 
\begin{align}
    p(x) = y_0\frac{(x-x_1)(x-x_2)\cdots(x-x_n)}{(x_0-x_1)(x_0-x_2)\cdots(x_0-x_n)}+y_1\frac{(x-x_0)(x-x_2)\cdots(x-x_n)}{(x_1-x_0)(x_1-x_2)\cdots(x_1-x_n)}\\
    +\cdots+y_n\frac{(x-x_0)(x-x_1)\cdots(x-x_{n-1})}{(x_n-x_0)(x_n-x_1)\cdots(x_n-x_{n-1})}
\end{align}
* Lagrange error formula
\begin{align}
f(x) = p(x) + \frac{f^{(n+1)}(\xi(x))}{(n+1)！} (x-x_0)\cdots (x-x_n).
\end{align}
* Piecewise linear interpolation


## Compute the value $p(a)$ at $x=a$ without constructing the polynomial $p(x)$

* For example, the population at 1965 can be obtained without constructing the Lagrange interpolation polynomial directly. 
* Neville's method
\begin{theorem}
The Lagrange interpolation polynomial is equivalent to 
    \begin{align}
    p_{0,1,\cdots,n}(x) =& \frac{x-x_j}{x_i-x_j}p_{0,1,\cdots,j-1,j+1,\cdots,n}(x)+\frac{x-x_i}{x_j-x_i}p_{0,1,\cdots,i-1,i+1,\cdots,n}(x)\\
    =& \frac{1}{x_i-x_j}[(x-x_j)p_{0,1,\cdots,j-1,j+1,\cdots,n}(x)-(x-x_i)p_{0,1,\cdots,i-1,i+1,\cdots,n}(x)]
    \end{align}
    for $i\neq j$.
\end{theorem}
* Proof
* It is an iterative algorithm

## Example

The table lists values of $f$ at various points. Compute $f(1.5)$ by various Lagrange interpolation polynomials.

| $x$ 	| $f(x)$    	|
|-----	|-----------	|
| 1.0 	| 0.7651977 	|
| 1.3 	| 0.6200860 	|
| 1.6 	| 0.4554022 	|
| 1.9 	| 0.2818186 	|
| 2.2 	| 0.1103623 	|

## Neville's table
|       	|       	|           	|             	|               	|                 	|
|-------	|-------	|-----------	|-------------	|---------------	|-----------------	|
| $x_0$ 	| $p_0$ 	|           	|             	|               	|                 	|
| $x_1$ 	| $p_1$ 	| $p_{0,1}$ 	|             	|               	|                 	|
| $x_2$ 	| $p_2$ 	| $p_{1,2}$ 	| $p_{0,1,2}$ 	|               	|                 	|
| $x_3$ 	| $p_3$ 	| $p_{2,3}$ 	| $p_{1,2,3}$ 	| $p_{0,1,2,3}$ 	|                 	|
| $x_4$ 	| $p_4$ 	| $p_{3,4}$ 	| $p_{2,3,4}$ 	| $p_{1,2,3,4}$ 	| $p_{0,1,2,3,4}$ 	|

In [17]:
function get_Neville_table(xn,yn,x)
    N = length(xn)
    nt= zeros((N,N))
    nt[:,1] = yn
    for j in 2:N
        for i in j:N
            nt[i,j] = ((x-xn[i-j+1])*nt[i,j-1]-(x-xn[i])*nt[i-1,j-1])/(xn[i]-xn[i-j+1])
        end
    end
    return nt
end

get_Neville_table (generic function with 1 method)

In [43]:
xn = [1.0,1.3,1.6,1.9,2.2]
yn = [0.7651977,0.6200860,0.4554022,0.2818186,0.1103623]
nt = get_Neville_table(xn,yn,1.5)

5×5 Array{Float64,2}:
 0.765198  0.0       0.0       0.0       0.0
 0.620086  0.523345  0.0       0.0       0.0
 0.455402  0.510297  0.512471  0.0       0.0
 0.281819  0.513263  0.511286  0.511813  0.0
 0.110362  0.510427  0.513736  0.51183   0.51182

In [44]:
xn = [1.0,1.3,1.6,1.9,2.2,2.5]
yn = [0.7651977,0.6200860,0.4554022,0.2818186,0.1103623,-0.0483838]
nt = get_Neville_table(xn,yn,1.5)

6×6 Array{Float64,2}:
  0.765198   0.0       0.0       0.0       0.0       0.0
  0.620086   0.523345  0.0       0.0       0.0       0.0
  0.455402   0.510297  0.512471  0.0       0.0       0.0
  0.281819   0.513263  0.511286  0.511813  0.0       0.0
  0.110362   0.510427  0.513736  0.51183   0.51182   0.0
 -0.0483838  0.48077   0.530198  0.511907  0.511843  0.511828

## Example

Use Neville's method and four-digit rounding arithmetic to approximate $f(2.1)=ln(2.1)$ by completing the Neville table.

In [45]:
xn = [2.0,2.2,2.3]
yn = [0.6931,0.7885,0.8329]
nt = get_Neville_table(xn,yn,2.1)

3×3 Array{Float64,2}:
 0.6931  0.0     0.0
 0.7885  0.7408  0.0
 0.8329  0.7441  0.7419

In [46]:
abs(nt[end,end]-log(2.1))## You cannot expect more accuracy than the arithmetic provides.

3.734472937744204e-5

## Newton's divided-difference formula

* Q: $L_{n,k}$ has to be computed again if another new point is provided.
* A: assume the polynomial is in the form of 
\begin{align}
    p(x)=a_0+a_1(x-x_0)+a_2(x-x_0)(x-x_1)+\cdots+a_n(x-x_0)\cdots(x-x_n)
\end{align}

## Divided difference

1. $a_0=f(x_0)=:f[x_0]$
2. $a_1=\frac{f(x_1)-f(x_0)}{x_1-x_0}=:f[x_0,x_1]$
    * $f[x_0,x_1]=f[x_1,x_0]$
3. $a_2=\frac{f(x_2)-a_0-a_1(x_2-x_0)}{(x_2-x_0)(x_2-x_1)}=\frac{f[x_0,x_2]-f[x_0,x_1]}{x_2-x_1}=:f[x_0,x_1,x_2]$
    * $f[x_0,x_1,x_2]=f[x_1,x_0,x_2]=\cdots$
    * Because the coefficient of $x^2$ must be equal for the unique quadratic polynomial passing through $(x_0,y_0), (x_1,y_1), (x_2,y_2)$.
    * Or proof by induction


    
<img src="images/newton-divided-difference.png"  height="100"/>


## Newton's divided-difference formula

\begin{align}
    p(x) = f[x_0]+f[x_0,x_1](x-x_0)+\cdots+f[x_0,x_1,\cdots,x_n](x-x_0)\cdots(x-x_{n-1})
\end{align}

In [98]:
function get_divided_difference(xn,yn)
    N = length(xn)
    fd= zeros(Float64,(N,N)) ## Use float32 to see the effect of round-off error
    fd[:,1] = yn
    for j in 2:N
        for i in j:N
            fd[i,j] = (fd[i,j-1]-fd[i-1,j-1])/(xn[i]-xn[i-j+1])
        end
    end
    return fd
end

get_divided_difference (generic function with 1 method)

In [99]:
function get_Newton_divided_difference_at_x(fd,xn,yn,x)
    y = fd[1,1]
    r = 1
    for i in 2:length(xn)
        r *= (x-xn[i-1])
        y += fd[i,i]*r
    end
    return y
end

get_Newton_divided_difference_at_x (generic function with 1 method)

In [100]:
xn = [1.0,1.3,1.6,1.9,2.2]
yn = [0.7651977,0.6200860,0.4554022,0.2818186,0.1103623]
newton_table = get_divided_difference(xn,yn)

5×5 Array{Float64,2}:
 0.765198   0.0        0.0        0.0        0.0
 0.620086  -0.483706   0.0        0.0        0.0
 0.455402  -0.548946  -0.108734   0.0        0.0
 0.281819  -0.578612  -0.0494433  0.0658784  0.0
 0.110362  -0.571521   0.0118183  0.0680685  0.0018251

In [101]:
get_Newton_divided_difference_at_x(newton_table,xn,yn,1.5)

0.5118199942386833

In [102]:
xn2 = [xn[i] for i in [3,2,4,1,5]]## independent of the order due to the uniqueness
yn2 = [yn[i] for i in [3,2,4,1,5]]
newton_table = get_divided_difference(xn2,yn2)
get_Newton_divided_difference_at_x(newton_table,xn2,yn2,1.5)

0.5118199942386831

In [103]:
xn2 = [xn[i] for i in [3,2,1]]## Backward-difference
yn2 = [yn[i] for i in [3,2,1]]
newton_table = get_divided_difference(xn2,yn2)
get_Newton_divided_difference_at_x(newton_table,xn2,yn2,1.5)

0.5124714777777778

In [104]:
xn2 = [xn[i] for i in [2,3,4]]## Forward-difference
yn2 = [yn[i] for i in [2,3,4]]
newton_table = get_divided_difference(xn2,yn2)
get_Newton_divided_difference_at_x(newton_table,xn2,yn2,1.5)

0.5112856666666666

In [105]:
xn2 = [xn[i] for i in [3,2,4,1]]## Stirling's
yn2 = [yn[i] for i in [3,2,4,1]]
newton_table = get_divided_difference(xn2,yn2)
get_Newton_divided_difference_at_x(newton_table,xn2,yn2,1.5)

0.5118126938271604

Assume the nodes are arranged consecutively with equal spacing $h$. Assume $x=x_0+sh$.
\begin{align}
p(x) =& f[x_0]+a_1(x-x_0)+\cdots a_n(x-x_0)\cdots(x-x_{n-1})\\
=& f[x_0] + f[x_0,x_1]sh + \cdots f[x_0,\cdots,x_n]sh(s-1)h\cdots(s-(n-1))h\\
=& f[x_0] + \sum_{k=1}^n {s\choose k} k!h^k f[x_0,\cdots,x_{k}]
\end{align}

## divided-difference $\approx$ derivative
\begin{theorem}
If

1. $x_i$ are distinct
2. $f\in C^{(n+1)}[a,b]$,

then there exists $\xi\in (a,b)$ such that 
\begin{align}
    f[x_0,x_1,\cdots,x_n] = \frac{f^{(n)}(\xi)}{n!}
\end{align}
\end{theorem}

+ Proof: Apply Roll's theorem to
\begin{align}
F(t):=f(t)-([x_0]+\cdots+[x_0,x_1,\cdots,x_n](t-x_0)\cdots(t-x_n))
\end{align}

## Newton forward-difference formula

Assume the nodes are arranged consecutively with equal spacing $h$.
\begin{align}
    f[x_0,x_1] = \frac{f(x_1)-f(x_0)}{x_1-x_0} = \frac{1}{h}(f(x_1)-f(x_0))=\frac{1}{h}\Delta f(x_0)\\
    f[x_0,x_1,x_2] = \frac{f[x_1,x_2]-f[x_0,x_1]}{x_2-x_0} = \frac{1}{2h}\frac{\Delta f(x_1)-\Delta f(x_0)}{h}=\frac{1}{2h^2}\Delta^2 f(x_0)\\
    \cdots\\
    f[x_0,x_1,\cdots,x_n] = \frac{1}{n!h^n}\Delta^n f(x_0)
\end{align}

Assume $x = x_0 + sh$.
\begin{align}
p(x) =& f[x_0]+a_1(x-x_0)+\cdots a_n(x-x_0)\cdots(x-x_{n-1})\\
=& f(x_0) + \frac{1}{h}\Delta f(x_0) sh + \frac{1}{2h^2}\Delta^2 f(x_0) sh (s-1)h+\cdots + \frac{1}{n!h^n}\Delta^n f(x_0) sh(s-1)h\cdots(s-(n-1))h\\
=& f(x_0) + \sum_{k=1}^n {s\choose k} \Delta^k f(x_0).
\end{align}

* When $x$ is near $x_0$, use the forward-difference formula.

## Newton backward-difference formula

Assume the nodes are arranged consecutively with equal spacing $h$.
\begin{align}
    f[x_0,x_1] =& \frac{f(x_1)-f(x_0)}{x_1-x_0} = \frac{1}{h}(f(x_1)-f(x_0))=\frac{1}{h}\nabla f(x_1)\\
    f[x_0,x_1,x_2] =& \frac{f[x_1,x_2]-f[x_0,x_1]}{x_2-x_0} = \frac{1}{2h}\frac{\nabla f(x_2)-\nabla f(x_1)}{h}=\frac{1}{2h^2}\nabla^2 f(x_2)\\
    \cdots\\
    f[x_0,x_1,\cdots,x_n] =& \frac{1}{n!h^n}\nabla^n f(x_n)
\end{align}

Assume $x = x_n + sh$.
\begin{align}
p(x) =& f[x_n]+f[x_n,x_{n-1}](x-x_n)+\cdots f[x_n,x_{n-1},\cdots,x_0](x-x_n)\cdots(x-x_{1})\\
=& f(x_n) + \frac{1}{h}\nabla f(x_n) sh + \frac{1}{2h^2}\nabla^2 f(x_n) sh (s+1)h+\cdots + \frac{1}{n!h^n}\nabla^n f(x_n) sh(s+1)h\cdots(s+(n-1))h\\
=& f(x_n) + \sum_{k=1}^n (-1)^k{-s\choose k} \nabla^k f(x_n).
\end{align}


* When $x$ is near $x_n$, use the forward-difference formula.

## Stirling's central-difference formula

1. Choose $x_0$ near the point $x$ being approximated
2. Label the nodes directly below as $x_1, x_2,\cdots$
3. Label the nodes directly above as $x_{-1},x_{-2},\cdots$

The Newton's divided-difference formula for $x_0,x_1,x_{-1},x_{2},x_{-2},\cdots$ is 
\begin{align}
    p(x) = f[x_0]+f[x_0,x_1](x-x_0)+f[x_0,x_1,x_{-1}](x-x_0)(x-x_1)+f[x_0,x_1,x_{-1},x_2](x-x_0)(x-x_1)(x-x_{-1})+f[x_0,x_1,x_{-1},x_2,x_{-2}](x-x_0)(x-x_1)(x-x_{-1})(x-x_2)+\cdots
\end{align}

The Newton's divided-difference formula for $x_0,x_{-1},x_1,x_{-2},x_{2},\cdots$ is 
\begin{align}
    p(x) = f[x_0]+f[x_0,x_{-1}](x-x_0)+f[x_0,x_{-1},x_{1}](x-x_0)(x-x_{-1})+f[x_0,x_{-1},x_{1},x_{-2}](x-x_0)(x-x_{-1})(x-x_{1})+f[x_0,x_{-1},x_{1},x_{-2},x_2](x-x_0)(x-x_{-1})(x-x_{1})(x-x_{-2})+\cdots
\end{align}

The average of these two formulas gives Stirling's central-difference formula.
\begin{align}
    p(x) = f[x_0]+\frac{1}{2}(f[x_0,x_{-1}]+f[x_0,x_1])(x-x_0)+f[x_0,x_{-1},x_{1}](x-x_0)(x-\frac{x_{-1}+x_1}{2})\\
    +\frac{1}{2}(f[x_0,x_1,x_{-1},x_2,x_{-2}]+f[x_0,x_{-1},x_{1},x_{-2}])(x-x_0)(x-x_{-1})(x-x_{1})\\
    +f[x_0,x_{-1},x_{1},x_{-2},x_2](x-x_0)(x-x_{-1})(x-x_{1})(x-\frac{x_{-2}+x_2}{2})+\cdots
\end{align}



## The effect of round-off error

1. If the fifth differences have the the sign almost alternating, the roundoff noise is dominating.
2. The we would not expect to go beyond fourth difference in any interpolation formula.

In [113]:
xn = collect(0.0:0.01:1.0)
yn = exp.(xn)
nt = get_divided_difference(xn,yn)

101×101 Array{Float64,2}:
 1.0      0.0      0.0       0.0       0.0        …   0.0         0.0
 1.01005  1.00502  0.0       0.0       0.0            0.0         0.0
 1.0202   1.01512  0.505029  0.0       0.0            0.0         0.0
 1.03045  1.02532  0.510105  0.169188  0.0            0.0         0.0
 1.04081  1.03562  0.515232  0.170888  0.0425091      0.0         0.0
 1.05127  1.04603  0.52041   0.172605  0.0429363  …   0.0         0.0
 1.06184  1.05655  0.52564   0.17434   0.0433678      0.0         0.0
 1.07251  1.06716  0.530923  0.176092  0.0438037      0.0         0.0
 1.08329  1.07789  0.536259  0.177862  0.0442439      0.0         0.0
 1.09417  1.08872  0.541648  0.17965   0.0446886      0.0         0.0
 1.10517  1.09966  0.547092  0.181455  0.0451377  …   0.0         0.0
 1.11628  1.11072  0.55259   0.183279  0.0455914      0.0         0.0
 1.1275   1.12188  0.558144  0.185121  0.0460496      0.0         0.0
 ⋮                                                ⋱             

In [123]:
nt[:,8:9]

101×2 Array{Float64,2}:
 0.0           0.0
 0.0           0.0
 0.0           0.0
 0.0           0.0
 0.0           0.0
 0.0           0.0
 0.0           0.0
 0.000304161   0.0
 0.000108169  -0.0024499
 0.00028116    0.0021624
 0.000177501  -0.00129574
 0.000213378   0.000448456
 0.00024437    0.0003874
 ⋮            
 0.000466999  -6.24628e-5
 0.000511055   0.000550705
 0.000370074  -0.00176226
 0.000625602   0.00319409
 0.00040532   -0.00275353
 0.000410987   7.08452e-5
 0.000670955   0.0032496
 0.000401937  -0.00336273
 0.000442327   0.000504876
 0.000692427   0.00312626
 0.000292295  -0.00500166
 0.000710515   0.00522775